<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
/** @var array $arParams */
/** @var array $arResult */
/** @global CMain $APPLICATION */
/** @global CUser $USER */
/** @global CDatabase $DB */
/** @var CBitrixComponentTemplate $this */
/** @var string $templateName */
/** @var string $templateFile */
/** @var string $templateFolder */
/** @var string $componentPath */
/** @var CBitrixComponent $component */
$this->setFrameMode(true);
?>

<?$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "",
    Array(
        "IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
        "IBLOCK_ID" => $arParams["IBLOCK_ID"],
        "NEWS_COUNT" => $arParams["NEWS_COUNT"],
        "SORT_BY1" => $arParams["SORT_BY1"],
        "SORT_ORDER1" => $arParams["SORT_ORDER1"],
        "SORT_BY2" => $arParams["SORT_BY2"],
        "SORT_ORDER2" => $arParams["SORT_ORDER2"],
        "FILTER_NAME" => $arParams["FILTER_NAME"],
        "FIELD_CODE" => $arParams["LIST_FIELD_CODE"],
        "PROPERTY_CODE" => $arParams["LIST_PROPERTY_CODE"],
        "CHECK_DATES" => $arParams["CHECK_DATES"],
        "DETAIL_URL" => $arParams["DETAIL_URL"],
        "AJAX_MODE" => $arParams["AJAX_MODE"],
        "AJAX_OPTION_JUMP" => $arParams["AJAX_OPTION_JUMP"],
        "AJAX_OPTION_STYLE" => $arParams["AJAX_OPTION_STYLE"],
        "AJAX_OPTION_HISTORY" => $arParams["AJAX_OPTION_HISTORY"],
        "CACHE_TYPE" => $arParams["CACHE_TYPE"],
        "CACHE_TIME" => $arParams["CACHE_TIME"],
        "CACHE_FILTER" => $arParams["CACHE_FILTER"],
        "CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
        "PREVIEW_TRUNCATE_LEN" => $arParams["PREVIEW_TRUNCATE_LEN"],
        "ACTIVE_DATE_FORMAT" => $arParams["LIST_ACTIVE_DATE_FORMAT"],
        "SET_TITLE" => $arParams["SET_TITLE"],
        "SET_BROWSER_TITLE" => $arParams["SET_BROWSER_TITLE"],
        "SET_META_KEYWORDS" => $arParams["SET_META_KEYWORDS"],
        "SET_META_DESCRIPTION" => $arParams["SET_META_DESCRIPTION"],
        "SET_LAST_MODIFIED" => $arParams["SET_LAST_MODIFIED"],
        "INCLUDE_IBLOCK_INTO_CHAIN" => $arParams["INCLUDE_IBLOCK_INTO_CHAIN"],
        "ADD_SECTIONS_CHAIN" => $arParams["ADD_SECTIONS_CHAIN"],
        "HIDE_LINK_WHEN_NO_DETAIL" => $arParams["HIDE_LINK_WHEN_NO_DETAIL"],
        "PARENT_SECTION" => $arParams["PARENT_SECTION"],
        "PARENT_SECTION_CODE" => $arParams["PARENT_SECTION_CODE"],
        "INCLUDE_SUBSECTIONS" => $arParams["INCLUDE_SUBSECTIONS"],
        "DISPLAY_DATE" => $arParams["DISPLAY_DATE"],
        "DISPLAY_NAME" => $arParams["DISPLAY_NAME"],
        "DISPLAY_PICTURE" => $arParams["DISPLAY_PICTURE"],
        "DISPLAY_PREVIEW_TEXT" => $arParams["DISPLAY_PREVIEW_TEXT"],
        "PAGER_TEMPLATE" => $arParams["PAGER_TEMPLATE"],
        "DISPLAY_TOP_PAGER" => $arParams["DISPLAY_TOP_PAGER"],
        "DISPLAY_BOTTOM_PAGER" => $arParams["DISPLAY_BOTTOM_PAGER"],
        "PAGER_TITLE" => $arParams["PAGER_TITLE"],
        "PAGER_SHOW_ALWAYS" => $arParams["PAGER_SHOW_ALWAYS"],
        "PAGER_DESC_NUMBERING" => $arParams["PAGER_DESC_NUMBERING"],
        "PAGER_DESC_NUMBERING_CACHE_TIME" => $arParams["PAGER_DESC_NUMBERING_CACHE_TIME"],
        "PAGER_SHOW_ALL" => $arParams["PAGER_SHOW_ALL"],
        "PAGER_BASE_LINK_ENABLE" => $arParams["PAGER_BASE_LINK_ENABLE"],
        "SET_STATUS_404" => $arParams["SET_STATUS_404"],
        "SHOW_404" => $arParams["SHOW_404"],
        "MESSAGE_404" => $arParams["MESSAGE_404"]
    ),
    $component
);?>

<?if($arResult["ID"]):?>
<?$APPLICATION->IncludeComponent(
    "bitrix:news.detail",
    "news_page_detail",
    Array(
        "IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
        "IBLOCK_ID" => $arParams["IBLOCK_ID"],
        "ELEMENT_ID" => $arResult["ID"],
        "ELEMENT_CODE" => $arResult["CODE"],
        "CHECK_DATES" => $arParams["CHECK_DATES"],
        "FIELD_CODE" => $arParams["DETAIL_FIELD_CODE"],
        "PROPERTY_CODE" => $arParams["DETAIL_PROPERTY_CODE"],
        "IBLOCK_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["news"],
        "DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["detail"],
        "CACHE_TYPE" => $arParams["CACHE_TYPE"],
        "CACHE_TIME" => $arParams["CACHE_TIME"],
        "CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
        "SET_TITLE" => $arParams["SET_TITLE"],
        "SET_CANONICAL_URL" => $arParams["DETAIL_SET_CANONICAL_URL"],
        "SET_BROWSER_TITLE" => $arParams["SET_BROWSER_TITLE"],
        "BROWSER_TITLE" => $arParams["DETAIL_BROWSER_TITLE"],
        "SET_META_KEYWORDS" => $arParams["SET_META_KEYWORDS"],
        "META_KEYWORDS" => $arParams["DETAIL_META_KEYWORDS"],
        "SET_META_DESCRIPTION" => $arParams["SET_META_DESCRIPTION"],
        "META_DESCRIPTION" => $arParams["DETAIL_META_DESCRIPTION"],
        "SET_LAST_MODIFIED" => $arParams["SET_LAST_MODIFIED"],
        "INCLUDE_IBLOCK_INTO_CHAIN" => $arParams["INCLUDE_IBLOCK_INTO_CHAIN"],
        "ADD_SECTIONS_CHAIN" => $arParams["ADD_SECTIONS_CHAIN"],
        "ADD_ELEMENT_CHAIN" => $arParams["ADD_ELEMENT_CHAIN"],
        "ACTIVE_DATE_FORMAT" => $arParams["DETAIL_ACTIVE_DATE_FORMAT"],
        "USE_PERMISSIONS" => $arParams["USE_PERMISSIONS"],
        "GROUP_PERMISSIONS" => $arParams["GROUP_PERMISSIONS"],
        "DISPLAY_DATE" => $arParams["DISPLAY_DATE"],
        "DISPLAY_NAME" => $arParams["DISPLAY_NAME"],
        "DISPLAY_PICTURE" => $arParams["DISPLAY_PICTURE"],
        "DISPLAY_PREVIEW_TEXT" => $arParams["DISPLAY_PREVIEW_TEXT"],
        "USE_SHARE" => $arParams["USE_SHARE"],
        "SHARE_HIDE" => $arParams["SHARE_HIDE"],
        "SHARE_TEMPLATE" => $arParams["SHARE_TEMPLATE"],
        "SHARE_HANDLERS" => $arParams["SHARE_HANDLERS"],
        "SHARE_SHORTEN_URL_LOGIN" => $arParams["SHARE_SHORTEN_URL_LOGIN"],
        "SHARE_SHORTEN_URL_KEY" => $arParams["SHARE_SHORTEN_URL_KEY"],
        "AJAX_MODE" => $arParams["AJAX_MODE"],
        "AJAX_OPTION_JUMP" => $arParams["AJAX_OPTION_JUMP"],
        "AJAX_OPTION_STYLE" => $arParams["AJAX_OPTION_STYLE"],
        "AJAX_OPTION_HISTORY" => $arParams["AJAX_OPTION_HISTORY"],
        "USE_RATING" => $arParams["USE_RATING"],
        "RATING_TYPE" => $arParams["RATING_TYPE"],
        "MAX_VOTE" => $arParams["MAX_VOTE"],
        "VOTE_NAMES" => $arParams["VOTE_NAMES"],
        "DISPLAY_AS_RATING" => $arParams["DETAIL_DISPLAY_AS_RATING"],
        "SHOW_RATING" => $arParams["SHOW_RATING"],
        "USE_RSS" => $arParams["USE_RSS"],
        "RSS_USER_ID" => $arParams["RSS_USER_ID"],
        "RSS_USE_RSS" => $arParams["RSS_USE_RSS"],
        "RSSTITLE" => $arParams["RSSTITLE"],
        "RSSDESCRIPTION" => $arParams["RSSDESCRIPTION"],
        "RSS_IN" => $arParams["RSS_IN"],
        "RSS_OUT" => $arParams["RSS_OUT"],
        "RSSALL" => $arParams["RSSALL"],
        "BLOG_USE" => $arParams["BLOG_USE"],
        "BLOG_URL" => $arParams["BLOG_URL"],
        "VK_USE" => $arParams["VK_USE"],
        "VK_API_ID" => $arParams["VK_API_ID"],
        "FB_USE" => $arParams["FB_USE"],
        "FB_APP_ID" => $arParams["FB_APP_ID"],
        "BRAND_USE" => $arParams["BRAND_USE"],
        "BRAND_PROP_CODE" => $arParams["BRAND_PROP_CODE"],
        "DISPLAY_TOP_PAGER" => $arParams["DETAIL_DISPLAY_TOP_PAGER"],
        "DISPLAY_BOTTOM_PAGER" => $arParams["DETAIL_DISPLAY_BOTTOM_PAGER"],
        "PAGER_TITLE" => $arParams["DETAIL_PAGER_TITLE"],
        "PAGER_TEMPLATE" => $arParams["DETAIL_PAGER_TEMPLATE"],
        "PAGER_SHOW_ALL" => $arParams["DETAIL_PAGER_SHOW_ALL"],
        "SET_STATUS_404" => $arParams["SET_STATUS_404"],
        "SHOW_404" => $arParams["SHOW_404"],
        "MESSAGE_404" => $arParams["MESSAGE_404"]
    ),
    $component
);?>
<?endif?>
